script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
env:
  - RAILS=3.2.17
  - RAILS=4.0.3
matrix:
  allow_failures:
