script: bundle exec rspec
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
env:
  - RAILS=3.2.22
  - RAILS=4.2.4
matrix:
  allow_failures:
